// <auto-generated />
using System;
using CodeCrafters.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CodeCrafters.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260313133112_AddOrganisationProfile")]
    partial class AddOrganisationProfile
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CodeCrafters.Domain.Entities.Grants.GrantType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AnnualCycle")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("EligibleApplicants")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<decimal>("FundingMaxAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FundingMinAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("GeographicFocus")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("MaximumAwardsPerCycle")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ProjectDurationMaxMonths")
                        .HasColumnType("int");

                    b.Property<int>("ProjectDurationMinMonths")
                        .HasColumnType("int");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<decimal>("TotalProgrammeBudget")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("GrantTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1111111-1111-1111-1111-111111111111"),
                            AnnualCycle = "Applications open April 1 – June 30 each year",
                            Code = "CDG",
                            EligibleApplicants = "Registered NGOs, Trusts, Section 8 Companies with minimum 2 years of operation",
                            FundingMaxAmount = 2000000m,
                            FundingMinAmount = 200000m,
                            GeographicFocus = "Rural and semi-urban areas in India",
                            MaximumAwardsPerCycle = 10,
                            Name = "Community Development Grant",
                            ProjectDurationMaxMonths = 18,
                            ProjectDurationMinMonths = 6,
                            Purpose = "Fund community-level infrastructure and social service projects",
                            TotalProgrammeBudget = 20000000m
                        },
                        new
                        {
                            Id = new Guid("a2222222-2222-2222-2222-222222222222"),
                            AnnualCycle = "Rolling applications — reviewed quarterly (Jan, Apr, Jul, Oct)",
                            Code = "EIG",
                            EligibleApplicants = "NGOs, EdTech non-profits, Research institutions, Universities (public or private)",
                            FundingMaxAmount = 5000000m,
                            FundingMinAmount = 500000m,
                            GeographicFocus = "Any state in India; preference for aspirational districts",
                            MaximumAwardsPerCycle = 5,
                            Name = "Education Innovation Grant",
                            ProjectDurationMaxMonths = 24,
                            ProjectDurationMinMonths = 12,
                            Purpose = "Fund technology-enabled or pedagogy-innovation projects improving learning outcomes in government schools",
                            TotalProgrammeBudget = 25000000m
                        },
                        new
                        {
                            Id = new Guid("a3333333-3333-3333-3333-333333333333"),
                            AnnualCycle = "Applications open twice yearly: Jan 1–Feb 28 and Jul 1–Aug 31",
                            Code = "ECAG",
                            EligibleApplicants = "NGOs, Farmer Producer Organisations (FPOs), Panchayat bodies, Research institutions",
                            FundingMaxAmount = 3000000m,
                            FundingMinAmount = 300000m,
                            GeographicFocus = "India — priority given to climate-vulnerable districts",
                            MaximumAwardsPerCycle = 15,
                            Name = "Environment & Climate Action Grant",
                            ProjectDurationMaxMonths = 24,
                            ProjectDurationMinMonths = 6,
                            Purpose = "Fund grassroots environmental conservation, climate resilience, and clean energy access projects",
                            TotalProgrammeBudget = 30000000m
                        });
                });

            modelBuilder.Entity("CodeCrafters.Domain.Entities.Organisations.Organisation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AnnualBudget")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ContactPersonEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ContactPersonName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ContactPersonPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsProfileComplete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Organisations", (string)null);
                });

            modelBuilder.Entity("CodeCrafters.Domain.Entities.SampleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SampleEntities");
                });

            modelBuilder.Entity("CodeCrafters.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CodeCrafters.Domain.Entities.Organisations.Organisation", b =>
                {
                    b.HasOne("CodeCrafters.Domain.Entities.User", "User")
                        .WithOne()
                        .HasForeignKey("CodeCrafters.Domain.Entities.Organisations.Organisation", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
