// <auto-generated />
using System;
using CodeCrafters.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CodeCrafters.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260313164257_SeedWorkflowStages")]
    partial class SeedWorkflowStages
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CodeCrafters.Domain.Entities.ApplicationReview", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("AiSuggestedScore")
                        .HasColumnType("int");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FinalScore")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ReviewStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("ReviewerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("SubmittedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("ReviewerId");

                    b.ToTable("ApplicationReviews");
                });

            modelBuilder.Entity("CodeCrafters.Domain.Entities.ApplicationWorkflowHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActionNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAiTriggered")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("StageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("StatusLabel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("TransitionedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("TriggeredByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("StageId");

                    b.HasIndex("TriggeredByUserId");

                    b.ToTable("ApplicationWorkflowHistories");
                });

            modelBuilder.Entity("CodeCrafters.Domain.Entities.Applications.Application", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActivityPlanForFirst6Months")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("AnnualOperatingBudget")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ApplicantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AuthorisedSignatoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BaselineAssessmentPlan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BeneficiaryDemographics")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BudgetJustification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClimateVulnerabilityContext")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("CommunityEngagementWages")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CommunityInvolvementPlan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ContentDevelopment")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CurrentStageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DirectBeneficiariesCount")
                        .HasColumnType("int");

                    b.Property<string>("EnvironmentalIndicators")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnvironmentalProblemDesc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("EquipmentAndMaterials")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("EvidenceBase")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExpectedOutcomes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GeographicCoverage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GovernmentPartnerships")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GradeLevelsTargeted")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("GrantTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("HasReceivedGrantsBefore")
                        .HasColumnType("bit");

                    b.Property<string>("InnovationDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InnovationType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("KeyActivitiesList")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KeyMilestones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KeyPartners")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LegalName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MeasurementPlan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NumberOfSchoolsTargeted")
                        .HasColumnType("int");

                    b.Property<int?>("NumberOfStudentsToBenefit")
                        .HasColumnType("int");

                    b.Property<string>("OrganisationType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("OtherCosts")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Overheads")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PersonnelCosts")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PrimaryContactEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrimaryContactName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrimaryContactPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrimaryLearningOutcome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PriorFunderNameAndAmount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProblemBeingSolved")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProblemStatement")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ProjectEndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProjectLeadNameAndExpertise")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectLeadNameAndQuals")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ProjectStartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProjectTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProposedIntervention")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProposedSolution")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReferenceNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RelevantPriorProjectsDesc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("RequestedAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RiskOfNotActing")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SaplingsAndSeeds")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset>("StageEnteredAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("StateOfRegistration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatusLabel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset?>("SubmissionDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("TargetBeneficiariesCount")
                        .HasColumnType("int");

                    b.Property<string>("TargetSchoolsDistricts")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeamDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeamExpertiseDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TeamSize")
                        .HasColumnType("int");

                    b.Property<decimal>("TechnologySoftware")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TechnologyToolsUsed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThematicArea")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("TotalRequestedAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TrainingAndWorkshops")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TravelAndLogistics")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YearOfEstablishment")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApplicantId");

                    b.HasIndex("CurrentStageId");

                    b.HasIndex("GrantTypeId");

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("CodeCrafters.Domain.Entities.GrantDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("DocumentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("GrantTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsMandatory")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("GrantTypeId");

                    b.ToTable("GrantDocuments", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("b1111111-1111-1111-1111-111111111111"),
                            DisplayOrder = 1,
                            DocumentName = "Organization Registration Certificate",
                            GrantTypeId = new Guid("a1111111-1111-1111-1111-111111111111"),
                            IsMandatory = true
                        },
                        new
                        {
                            Id = new Guid("b1111111-1111-1111-1111-222222222222"),
                            DisplayOrder = 2,
                            DocumentName = "Latest Audited Financial Statements",
                            GrantTypeId = new Guid("a1111111-1111-1111-1111-111111111111"),
                            IsMandatory = true
                        },
                        new
                        {
                            Id = new Guid("b1111111-1111-1111-1111-333333333333"),
                            DisplayOrder = 3,
                            DocumentName = "Project Proposal Document",
                            GrantTypeId = new Guid("a1111111-1111-1111-1111-111111111111"),
                            IsMandatory = true
                        },
                        new
                        {
                            Id = new Guid("b1111111-1111-1111-1111-444444444444"),
                            DisplayOrder = 4,
                            DocumentName = "Implementation Plan",
                            GrantTypeId = new Guid("a1111111-1111-1111-1111-111111111111"),
                            IsMandatory = true
                        },
                        new
                        {
                            Id = new Guid("b1111111-1111-1111-1111-555555555555"),
                            DisplayOrder = 5,
                            DocumentName = "Budget Breakdown",
                            GrantTypeId = new Guid("a1111111-1111-1111-1111-111111111111"),
                            IsMandatory = true
                        },
                        new
                        {
                            Id = new Guid("b1111111-1111-1111-1111-666666666666"),
                            DisplayOrder = 6,
                            DocumentName = "Letters of Community Support",
                            GrantTypeId = new Guid("a1111111-1111-1111-1111-111111111111"),
                            IsMandatory = false
                        },
                        new
                        {
                            Id = new Guid("b2222222-2222-2222-2222-111111111111"),
                            DisplayOrder = 1,
                            DocumentName = "Organization Registration Certificate",
                            GrantTypeId = new Guid("a2222222-2222-2222-2222-222222222222"),
                            IsMandatory = true
                        },
                        new
                        {
                            Id = new Guid("b2222222-2222-2222-2222-222222222222"),
                            DisplayOrder = 2,
                            DocumentName = "Project Concept Note",
                            GrantTypeId = new Guid("a2222222-2222-2222-2222-222222222222"),
                            IsMandatory = true
                        },
                        new
                        {
                            Id = new Guid("b2222222-2222-2222-2222-333333333333"),
                            DisplayOrder = 3,
                            DocumentName = "Detailed Project Proposal",
                            GrantTypeId = new Guid("a2222222-2222-2222-2222-222222222222"),
                            IsMandatory = true
                        },
                        new
                        {
                            Id = new Guid("b2222222-2222-2222-2222-444444444444"),
                            DisplayOrder = 4,
                            DocumentName = "Technology Solution Description",
                            GrantTypeId = new Guid("a2222222-2222-2222-2222-222222222222"),
                            IsMandatory = true
                        },
                        new
                        {
                            Id = new Guid("b2222222-2222-2222-2222-555555555555"),
                            DisplayOrder = 5,
                            DocumentName = "Budget Plan",
                            GrantTypeId = new Guid("a2222222-2222-2222-2222-222222222222"),
                            IsMandatory = true
                        },
                        new
                        {
                            Id = new Guid("b2222222-2222-2222-2222-666666666666"),
                            DisplayOrder = 6,
                            DocumentName = "Past Impact Evidence",
                            GrantTypeId = new Guid("a2222222-2222-2222-2222-222222222222"),
                            IsMandatory = false
                        },
                        new
                        {
                            Id = new Guid("b3333333-3333-3333-3333-111111111111"),
                            DisplayOrder = 1,
                            DocumentName = "Organization Registration Certificate",
                            GrantTypeId = new Guid("a3333333-3333-3333-3333-333333333333"),
                            IsMandatory = true
                        },
                        new
                        {
                            Id = new Guid("b3333333-3333-3333-3333-222222222222"),
                            DisplayOrder = 2,
                            DocumentName = "Environmental Impact Description",
                            GrantTypeId = new Guid("a3333333-3333-3333-3333-333333333333"),
                            IsMandatory = true
                        },
                        new
                        {
                            Id = new Guid("b3333333-3333-3333-3333-333333333333"),
                            DisplayOrder = 3,
                            DocumentName = "Project Proposal",
                            GrantTypeId = new Guid("a3333333-3333-3333-3333-333333333333"),
                            IsMandatory = true
                        },
                        new
                        {
                            Id = new Guid("b3333333-3333-3333-3333-444444444444"),
                            DisplayOrder = 4,
                            DocumentName = "Implementation Timeline",
                            GrantTypeId = new Guid("a3333333-3333-3333-3333-333333333333"),
                            IsMandatory = true
                        },
                        new
                        {
                            Id = new Guid("b3333333-3333-3333-3333-555555555555"),
                            DisplayOrder = 5,
                            DocumentName = "Budget Plan",
                            GrantTypeId = new Guid("a3333333-3333-3333-3333-333333333333"),
                            IsMandatory = true
                        },
                        new
                        {
                            Id = new Guid("b3333333-3333-3333-3333-666666666666"),
                            DisplayOrder = 6,
                            DocumentName = "Community Partnership Letters",
                            GrantTypeId = new Guid("a3333333-3333-3333-3333-333333333333"),
                            IsMandatory = false
                        });
                });

            modelBuilder.Entity("CodeCrafters.Domain.Entities.GrantType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AnnualCycle")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("EligibleApplicants")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<decimal>("FundingMaxAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FundingMinAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("GeographicFocus")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("MaximumAwardsPerCycle")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ProjectDurationMaxMonths")
                        .HasColumnType("int");

                    b.Property<int>("ProjectDurationMinMonths")
                        .HasColumnType("int");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<decimal>("TotalProgrammeBudget")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("GrantTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1111111-1111-1111-1111-111111111111"),
                            AnnualCycle = "Applications open April 1 – June 30 each year",
                            Code = "CDG",
                            EligibleApplicants = "Registered NGOs, Trusts, Section 8 Companies with minimum 2 years of operation",
                            FundingMaxAmount = 2000000m,
                            FundingMinAmount = 200000m,
                            GeographicFocus = "Rural and semi-urban areas in India",
                            MaximumAwardsPerCycle = 10,
                            Name = "Community Development Grant",
                            ProjectDurationMaxMonths = 18,
                            ProjectDurationMinMonths = 6,
                            Purpose = "Fund community-level infrastructure and social service projects",
                            TotalProgrammeBudget = 20000000m
                        },
                        new
                        {
                            Id = new Guid("a2222222-2222-2222-2222-222222222222"),
                            AnnualCycle = "Rolling applications — reviewed quarterly (Jan, Apr, Jul, Oct)",
                            Code = "EIG",
                            EligibleApplicants = "NGOs, EdTech non-profits, Research institutions, Universities (public or private)",
                            FundingMaxAmount = 5000000m,
                            FundingMinAmount = 500000m,
                            GeographicFocus = "Any state in India; preference for aspirational districts",
                            MaximumAwardsPerCycle = 5,
                            Name = "Education Innovation Grant",
                            ProjectDurationMaxMonths = 24,
                            ProjectDurationMinMonths = 12,
                            Purpose = "Fund technology-enabled or pedagogy-innovation projects improving learning outcomes in government schools",
                            TotalProgrammeBudget = 25000000m
                        },
                        new
                        {
                            Id = new Guid("a3333333-3333-3333-3333-333333333333"),
                            AnnualCycle = "Applications open twice yearly: Jan 1–Feb 28 and Jul 1–Aug 31",
                            Code = "ECAG",
                            EligibleApplicants = "NGOs, Farmer Producer Organisations (FPOs), Panchayat bodies, Research institutions",
                            FundingMaxAmount = 3000000m,
                            FundingMinAmount = 300000m,
                            GeographicFocus = "India — priority given to climate-vulnerable districts",
                            MaximumAwardsPerCycle = 15,
                            Name = "Environment & Climate Action Grant",
                            ProjectDurationMaxMonths = 24,
                            ProjectDurationMinMonths = 6,
                            Purpose = "Fund grassroots environmental conservation, climate resilience, and clean energy access projects",
                            TotalProgrammeBudget = 30000000m
                        });
                });

            modelBuilder.Entity("CodeCrafters.Domain.Entities.GrantWorkflowStage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AssigneeRole")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("GrantTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("OrderIdx")
                        .HasColumnType("int");

                    b.Property<int>("RequiredReviewers")
                        .HasColumnType("int");

                    b.Property<int?>("SlaDays")
                        .HasColumnType("int");

                    b.Property<string>("SlaType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GrantTypeId");

                    b.ToTable("GrantWorkflowStages");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c1111111-0001-0001-0001-111111111111"),
                            AssigneeRole = "System",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrantTypeId = new Guid("a1111111-1111-1111-1111-111111111111"),
                            IsDeleted = false,
                            Name = "Submitted",
                            OrderIdx = 1,
                            RequiredReviewers = 0,
                            SlaType = "Instant",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("c1111111-0001-0001-0002-111111111111"),
                            AssigneeRole = "AI Agent",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrantTypeId = new Guid("a1111111-1111-1111-1111-111111111111"),
                            IsDeleted = false,
                            Name = "Eligibility Screening",
                            OrderIdx = 2,
                            RequiredReviewers = 0,
                            SlaDays = 1,
                            SlaType = "Working Days",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("c1111111-0001-0001-0003-111111111111"),
                            AssigneeRole = "Program Officer",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrantTypeId = new Guid("a1111111-1111-1111-1111-111111111111"),
                            IsDeleted = false,
                            Name = "Under Review",
                            OrderIdx = 3,
                            RequiredReviewers = 1,
                            SlaDays = 14,
                            SlaType = "Working Days",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("c1111111-0001-0001-0004-111111111111"),
                            AssigneeRole = "Program Officer",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrantTypeId = new Guid("a1111111-1111-1111-1111-111111111111"),
                            IsDeleted = false,
                            Name = "Award Decision",
                            OrderIdx = 4,
                            RequiredReviewers = 0,
                            SlaDays = 7,
                            SlaType = "Working Days",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("c1111111-0001-0001-0005-111111111111"),
                            AssigneeRole = "Program Officer",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrantTypeId = new Guid("a1111111-1111-1111-1111-111111111111"),
                            IsDeleted = false,
                            Name = "Agreement Sent",
                            OrderIdx = 5,
                            RequiredReviewers = 0,
                            SlaDays = 5,
                            SlaType = "Working Days",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("c1111111-0001-0001-0006-111111111111"),
                            AssigneeRole = "Applicant",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrantTypeId = new Guid("a1111111-1111-1111-1111-111111111111"),
                            IsDeleted = false,
                            Name = "Active Grant",
                            OrderIdx = 6,
                            RequiredReviewers = 0,
                            SlaType = "N/A",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("c1111111-0001-0001-0007-111111111111"),
                            AssigneeRole = "Applicant",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrantTypeId = new Guid("a1111111-1111-1111-1111-111111111111"),
                            IsDeleted = false,
                            Name = "Reporting",
                            OrderIdx = 7,
                            RequiredReviewers = 0,
                            SlaDays = 30,
                            SlaType = "Calendar Days",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("c1111111-0001-0001-0008-111111111111"),
                            AssigneeRole = "System",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrantTypeId = new Guid("a1111111-1111-1111-1111-111111111111"),
                            IsDeleted = false,
                            Name = "Closed",
                            OrderIdx = 8,
                            RequiredReviewers = 0,
                            SlaType = "Instant",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("e2222222-0002-0002-0001-222222222222"),
                            AssigneeRole = "System",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrantTypeId = new Guid("a2222222-2222-2222-2222-222222222222"),
                            IsDeleted = false,
                            Name = "Submitted",
                            OrderIdx = 1,
                            RequiredReviewers = 0,
                            SlaType = "Instant",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("e2222222-0002-0002-0002-222222222222"),
                            AssigneeRole = "AI Agent",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrantTypeId = new Guid("a2222222-2222-2222-2222-222222222222"),
                            IsDeleted = false,
                            Name = "Eligibility Screening",
                            OrderIdx = 2,
                            RequiredReviewers = 0,
                            SlaDays = 1,
                            SlaType = "Working Days",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("e2222222-0002-0002-0003-222222222222"),
                            AssigneeRole = "Grant Reviewer",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrantTypeId = new Guid("a2222222-2222-2222-2222-222222222222"),
                            IsDeleted = false,
                            Name = "Under Review",
                            OrderIdx = 3,
                            RequiredReviewers = 2,
                            SlaDays = 21,
                            SlaType = "Working Days",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("e2222222-0002-0002-0004-222222222222"),
                            AssigneeRole = "Program Officer",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrantTypeId = new Guid("a2222222-2222-2222-2222-222222222222"),
                            IsDeleted = false,
                            Name = "Award Decision",
                            OrderIdx = 4,
                            RequiredReviewers = 0,
                            SlaDays = 7,
                            SlaType = "Working Days",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("e2222222-0002-0002-0005-222222222222"),
                            AssigneeRole = "Program Officer",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrantTypeId = new Guid("a2222222-2222-2222-2222-222222222222"),
                            IsDeleted = false,
                            Name = "Agreement Sent",
                            OrderIdx = 5,
                            RequiredReviewers = 0,
                            SlaDays = 5,
                            SlaType = "Working Days",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("e2222222-0002-0002-0006-222222222222"),
                            AssigneeRole = "Applicant",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrantTypeId = new Guid("a2222222-2222-2222-2222-222222222222"),
                            IsDeleted = false,
                            Name = "Active Grant",
                            OrderIdx = 6,
                            RequiredReviewers = 0,
                            SlaType = "N/A",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("e2222222-0002-0002-0007-222222222222"),
                            AssigneeRole = "Applicant",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrantTypeId = new Guid("a2222222-2222-2222-2222-222222222222"),
                            IsDeleted = false,
                            Name = "Reporting",
                            OrderIdx = 7,
                            RequiredReviewers = 0,
                            SlaDays = 30,
                            SlaType = "Calendar Days",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("e2222222-0002-0002-0008-222222222222"),
                            AssigneeRole = "System",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrantTypeId = new Guid("a2222222-2222-2222-2222-222222222222"),
                            IsDeleted = false,
                            Name = "Closed",
                            OrderIdx = 8,
                            RequiredReviewers = 0,
                            SlaType = "Instant",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("f3333333-0003-0003-0001-333333333333"),
                            AssigneeRole = "System",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrantTypeId = new Guid("a3333333-3333-3333-3333-333333333333"),
                            IsDeleted = false,
                            Name = "Submitted",
                            OrderIdx = 1,
                            RequiredReviewers = 0,
                            SlaType = "Instant",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("f3333333-0003-0003-0002-333333333333"),
                            AssigneeRole = "AI Agent",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrantTypeId = new Guid("a3333333-3333-3333-3333-333333333333"),
                            IsDeleted = false,
                            Name = "Eligibility Screening",
                            OrderIdx = 2,
                            RequiredReviewers = 0,
                            SlaDays = 1,
                            SlaType = "Working Days",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("f3333333-0003-0003-0003-333333333333"),
                            AssigneeRole = "Program Officer",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrantTypeId = new Guid("a3333333-3333-3333-3333-333333333333"),
                            IsDeleted = false,
                            Name = "Under Review",
                            OrderIdx = 3,
                            RequiredReviewers = 1,
                            SlaDays = 14,
                            SlaType = "Working Days",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("f3333333-0003-0003-0004-333333333333"),
                            AssigneeRole = "Program Officer",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrantTypeId = new Guid("a3333333-3333-3333-3333-333333333333"),
                            IsDeleted = false,
                            Name = "Award Decision",
                            OrderIdx = 4,
                            RequiredReviewers = 0,
                            SlaDays = 7,
                            SlaType = "Working Days",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("f3333333-0003-0003-0005-333333333333"),
                            AssigneeRole = "Program Officer",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrantTypeId = new Guid("a3333333-3333-3333-3333-333333333333"),
                            IsDeleted = false,
                            Name = "Agreement Sent",
                            OrderIdx = 5,
                            RequiredReviewers = 0,
                            SlaDays = 5,
                            SlaType = "Working Days",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("f3333333-0003-0003-0006-333333333333"),
                            AssigneeRole = "Applicant",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrantTypeId = new Guid("a3333333-3333-3333-3333-333333333333"),
                            IsDeleted = false,
                            Name = "Active Grant",
                            OrderIdx = 6,
                            RequiredReviewers = 0,
                            SlaType = "N/A",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("f3333333-0003-0003-0007-333333333333"),
                            AssigneeRole = "Applicant",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrantTypeId = new Guid("a3333333-3333-3333-3333-333333333333"),
                            IsDeleted = false,
                            Name = "Reporting",
                            OrderIdx = 7,
                            RequiredReviewers = 0,
                            SlaDays = 30,
                            SlaType = "Calendar Days",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("f3333333-0003-0003-0008-333333333333"),
                            AssigneeRole = "System",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrantTypeId = new Guid("a3333333-3333-3333-3333-333333333333"),
                            IsDeleted = false,
                            Name = "Closed",
                            OrderIdx = 8,
                            RequiredReviewers = 0,
                            SlaType = "Instant",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("CodeCrafters.Domain.Entities.Organisations.Organisation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AnnualBudget")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ContactPersonEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ContactPersonName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ContactPersonPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsProfileComplete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Organisations", (string)null);
                });

            modelBuilder.Entity("CodeCrafters.Domain.Entities.SampleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SampleEntities");
                });

            modelBuilder.Entity("CodeCrafters.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("OrganisationName")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CodeCrafters.Domain.Entities.UserDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("StoredPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserDocuments", (string)null);
                });

            modelBuilder.Entity("CodeCrafters.Domain.Entities.ApplicationReview", b =>
                {
                    b.HasOne("CodeCrafters.Domain.Entities.Applications.Application", "Application")
                        .WithMany()
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CodeCrafters.Domain.Entities.User", "Reviewer")
                        .WithMany()
                        .HasForeignKey("ReviewerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("Reviewer");
                });

            modelBuilder.Entity("CodeCrafters.Domain.Entities.ApplicationWorkflowHistory", b =>
                {
                    b.HasOne("CodeCrafters.Domain.Entities.Applications.Application", "Application")
                        .WithMany("WorkflowHistories")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CodeCrafters.Domain.Entities.GrantWorkflowStage", "Stage")
                        .WithMany()
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CodeCrafters.Domain.Entities.User", "TriggeredByUser")
                        .WithMany()
                        .HasForeignKey("TriggeredByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Application");

                    b.Navigation("Stage");

                    b.Navigation("TriggeredByUser");
                });

            modelBuilder.Entity("CodeCrafters.Domain.Entities.Applications.Application", b =>
                {
                    b.HasOne("CodeCrafters.Domain.Entities.User", "Applicant")
                        .WithMany()
                        .HasForeignKey("ApplicantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CodeCrafters.Domain.Entities.GrantWorkflowStage", "CurrentStage")
                        .WithMany()
                        .HasForeignKey("CurrentStageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CodeCrafters.Domain.Entities.GrantType", "GrantType")
                        .WithMany()
                        .HasForeignKey("GrantTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Applicant");

                    b.Navigation("CurrentStage");

                    b.Navigation("GrantType");
                });

            modelBuilder.Entity("CodeCrafters.Domain.Entities.GrantDocument", b =>
                {
                    b.HasOne("CodeCrafters.Domain.Entities.GrantType", "GrantType")
                        .WithMany("RequiredDocuments")
                        .HasForeignKey("GrantTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GrantType");
                });

            modelBuilder.Entity("CodeCrafters.Domain.Entities.GrantWorkflowStage", b =>
                {
                    b.HasOne("CodeCrafters.Domain.Entities.GrantType", "GrantType")
                        .WithMany("WorkflowStages")
                        .HasForeignKey("GrantTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GrantType");
                });

            modelBuilder.Entity("CodeCrafters.Domain.Entities.Organisations.Organisation", b =>
                {
                    b.HasOne("CodeCrafters.Domain.Entities.User", "User")
                        .WithOne()
                        .HasForeignKey("CodeCrafters.Domain.Entities.Organisations.Organisation", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CodeCrafters.Domain.Entities.UserDocument", b =>
                {
                    b.HasOne("CodeCrafters.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CodeCrafters.Domain.Entities.Applications.Application", b =>
                {
                    b.Navigation("WorkflowHistories");
                });

            modelBuilder.Entity("CodeCrafters.Domain.Entities.GrantType", b =>
                {
                    b.Navigation("RequiredDocuments");

                    b.Navigation("WorkflowStages");
                });
#pragma warning restore 612, 618
        }
    }
}
